"""Incident claim data model and wire format (R3b-2, spec R-M15 through R-M18).

A Claim represents an agent's assertion of ownership over an incident
investigation.  Claims are Ed25519-signed by the claimant and verified
by peers using the PeerKeyRing.

Key invariants from the spec:
  - R-M15: First-claim wins.  Tiebreak on stable node identity (agent_id),
    NOT on timestamp (clocks drift under network impairment).
  - R-M16: Claim subject is always the *device*, never the link.  Whether
    the fault is device or link is a conclusion, not the subject.
  - R-M17: Ownership held under a lease.  Lapsed lease returns the incident
    to claimable state, inheriting gathered evidence.
  - R-M18: Owner owns the investigation.  Resolution belongs to SM/CC.
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from typing import Optional

from harkeniq.models import ClaimStatus

# Default claim lease: 120s (shorter than SM auth lease 300s so claim lapse
# is detected before authorization lapse).
DEFAULT_CLAIM_LEASE_DURATION = 120.0


def _canonical_json(d: dict) -> bytes:
    return json.dumps(d, sort_keys=True, separators=(",", ":")).encode("utf-8")


@dataclass
class Claim:
    """An incident ownership claim broadcast to peers.

    The claim_id is a UUID generated by the claimant.  The subject is
    always a device (R-M16), identified by subject_device_id (the device's
    agent_id, which is the identifier in the peer mesh).
    """

    claim_id: str
    claimant_id: str         # agent_id of the claiming agent
    subject_device_id: str   # always the device (R-M16)
    evidence: dict           # compact evidence snapshot
    seq: int                 # monotonic per claimant
    created_at: float        # informational only, NOT used for tiebreak
    signature: bytes = b""   # Ed25519 signature over canonical payload

    @staticmethod
    def new(
        claimant_id: str,
        subject_device_id: str,
        evidence: dict,
        seq: int,
    ) -> Claim:
        """Create a new unsigned claim."""
        return Claim(
            claim_id=str(uuid.uuid4()),
            claimant_id=claimant_id,
            subject_device_id=subject_device_id,
            evidence=evidence,
            seq=seq,
            created_at=time.time(),
        )

    def payload_bytes(self) -> bytes:
        """Canonical JSON of the claim payload (excludes signature)."""
        return _canonical_json({
            "claim_id": self.claim_id,
            "claimant_id": self.claimant_id,
            "subject_device_id": self.subject_device_id,
            "evidence": self.evidence,
            "seq": self.seq,
            "created_at": self.created_at,
        })

    def sign(self, private_key) -> None:
        """Sign the claim with the agent's Ed25519 private key."""
        self.signature = private_key.sign(self.payload_bytes())

    def verify(self, public_key) -> bool:
        """Verify the claim signature with the claimant's public key."""
        from cryptography.exceptions import InvalidSignature
        try:
            public_key.verify(self.signature, self.payload_bytes())
            return True
        except InvalidSignature:
            return False

    def serialize(self) -> bytes:
        """Serialize to wire format: canonical JSON + signature (64 bytes)."""
        return self.payload_bytes() + self.signature

    @staticmethod
    def deserialize(data: bytes) -> Claim:
        """Deserialize from wire format."""
        if len(data) < 65:
            raise ValueError("Claim data too short (need payload + 64-byte signature)")
        payload_bytes = data[:-64]
        signature = data[-64:]
        try:
            payload = json.loads(payload_bytes.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as e:
            raise ValueError(f"Malformed claim payload: {e}") from e
        return Claim(
            claim_id=str(payload["claim_id"]),
            claimant_id=str(payload["claimant_id"]),
            subject_device_id=str(payload["subject_device_id"]),
            evidence=dict(payload.get("evidence", {})),
            seq=int(payload["seq"]),
            created_at=float(payload["created_at"]),
            signature=signature,
        )


@dataclass
class ClaimAck:
    """Acknowledgment of a received claim."""

    claim_id: str
    acker_id: str    # agent_id of the acknowledging agent
    accepted: bool   # True = accepted, False = rejected (tiebreak loss)
    signature: bytes = b""

    def payload_bytes(self) -> bytes:
        return _canonical_json({
            "claim_id": self.claim_id,
            "acker_id": self.acker_id,
            "accepted": self.accepted,
        })

    def sign(self, private_key) -> None:
        self.signature = private_key.sign(self.payload_bytes())

    def verify(self, public_key) -> bool:
        from cryptography.exceptions import InvalidSignature
        try:
            public_key.verify(self.signature, self.payload_bytes())
            return True
        except InvalidSignature:
            return False

    def serialize(self) -> bytes:
        return self.payload_bytes() + self.signature

    @staticmethod
    def deserialize(data: bytes) -> ClaimAck:
        if len(data) < 65:
            raise ValueError("ClaimAck data too short")
        payload_bytes = data[:-64]
        signature = data[-64:]
        payload = json.loads(payload_bytes.decode("utf-8"))
        return ClaimAck(
            claim_id=str(payload["claim_id"]),
            acker_id=str(payload["acker_id"]),
            accepted=bool(payload["accepted"]),
            signature=signature,
        )


@dataclass
class ClaimLease:
    """Ownership lease on a claimed incident (R-M17).

    The owner must renew before expiry.  A lapsed lease returns the
    incident to claimable state with inherited evidence.
    """

    claim_id: str
    owner_id: str
    subject_device_id: str
    lease_expiry: float
    evidence_accumulated: list[dict] = field(default_factory=list)
    status: ClaimStatus = ClaimStatus.ACTIVE

    def is_valid(self, now: Optional[float] = None) -> bool:
        """True if the lease has not expired."""
        return (now or time.time()) < self.lease_expiry

    def is_lapsed(self, now: Optional[float] = None) -> bool:
        """True if the lease has expired."""
        return (now or time.time()) >= self.lease_expiry

    def renew(self, duration: float = DEFAULT_CLAIM_LEASE_DURATION) -> None:
        """Renew the lease for another duration."""
        self.lease_expiry = time.time() + duration
        self.status = ClaimStatus.ACTIVE

    def lapse(self) -> list[dict]:
        """Mark the lease as lapsed, returning accumulated evidence (R-M17)."""
        self.status = ClaimStatus.LAPSED
        return list(self.evidence_accumulated)

    def add_evidence(self, evidence: dict) -> None:
        """Accumulate evidence during investigation."""
        self.evidence_accumulated.append(evidence)

    @staticmethod
    def from_claim(
        claim: Claim,
        duration: float = DEFAULT_CLAIM_LEASE_DURATION,
    ) -> ClaimLease:
        """Create a lease from an accepted claim."""
        return ClaimLease(
            claim_id=claim.claim_id,
            owner_id=claim.claimant_id,
            subject_device_id=claim.subject_device_id,
            lease_expiry=time.time() + duration,
            evidence_accumulated=[claim.evidence],
        )


def deterministic_tiebreak(claim_a: Claim, claim_b: Claim) -> Claim:
    """Resolve concurrent claims for the same subject (R-M15).

    The claim with the lexicographically lower claimant_id wins.
    agent_id = SHA-256(pubkey)[:16], which is stable and deterministic.
    NOT based on timestamp (clocks drift under network impairment).
    """
    if claim_a.claimant_id <= claim_b.claimant_id:
        return claim_a
    return claim_b
