"""QA-033 feedback half: sm_candidate_skills — LLM-generated skill queue.

Candidate skills generated by the SM's reasoning enrichment path, held
for the CC upflow (FleetSnapshot.candidate_skills, reported_to_cc flag).

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-26
"""

from alembic import op
import sqlalchemy as sa

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 0001 is a create_all from CURRENT models; only pre-QA-033 databases
    # need the CREATE. Idempotence is mandatory in this chain (see 0003).
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("sm_candidate_skills"):
        return
    op.create_table(
        "sm_candidate_skills",
        sa.Column("skill_id", sa.String(64), primary_key=True),
        sa.Column("yaml_text", sa.Text(), nullable=False),
        sa.Column("source_device", sa.String(64), nullable=False),
        sa.Column("source_component", sa.String(128), nullable=False),
        sa.Column("validation_state", sa.String(16), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column("dry_run_matches", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reported_to_cc", sa.Boolean(), nullable=False),
    )
    op.create_index(
        "ix_candidate_skills_source",
        "sm_candidate_skills",
        ["source_device", "source_component"],
    )


def downgrade() -> None:
    op.drop_table("sm_candidate_skills")
