# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from harkeniq.proto import harkeniq_pb2 as harkeniq__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in harkeniq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportVerdict = channel.unary_unary(
                '/harkeniq.v1.AgentService/ReportVerdict',
                request_serializer=harkeniq__pb2.VerdictReport.SerializeToString,
                response_deserializer=harkeniq__pb2.VerdictAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/harkeniq.v1.AgentService/Heartbeat',
                request_serializer=harkeniq__pb2.AgentHeartbeat.SerializeToString,
                response_deserializer=harkeniq__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/harkeniq.v1.AgentService/RegisterAgent',
                request_serializer=harkeniq__pb2.AgentRegistration.SerializeToString,
                response_deserializer=harkeniq__pb2.RegistrationAck.FromString,
                _registered_method=True)
        self.ReportAction = channel.unary_unary(
                '/harkeniq.v1.AgentService/ReportAction',
                request_serializer=harkeniq__pb2.ActionReport.SerializeToString,
                response_deserializer=harkeniq__pb2.ActionAck.FromString,
                _registered_method=True)
        self.PollActionDecisions = channel.unary_unary(
                '/harkeniq.v1.AgentService/PollActionDecisions',
                request_serializer=harkeniq__pb2.DecisionPoll.SerializeToString,
                response_deserializer=harkeniq__pb2.DecisionList.FromString,
                _registered_method=True)
        self.PushSkill = channel.unary_unary(
                '/harkeniq.v1.AgentService/PushSkill',
                request_serializer=harkeniq__pb2.SkillDistribution.SerializeToString,
                response_deserializer=harkeniq__pb2.SkillDistributionAck.FromString,
                _registered_method=True)
        self.PollDirectives = channel.unary_unary(
                '/harkeniq.v1.AgentService/PollDirectives',
                request_serializer=harkeniq__pb2.DirectivePoll.SerializeToString,
                response_deserializer=harkeniq__pb2.DirectiveList.FromString,
                _registered_method=True)
        self.ReportDirectiveResult = channel.unary_unary(
                '/harkeniq.v1.AgentService/ReportDirectiveResult',
                request_serializer=harkeniq__pb2.DirectiveResult.SerializeToString,
                response_deserializer=harkeniq__pb2.DirectiveAck.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportVerdict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollActionDecisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushSkill(self, request, context):
        """R3b-1 C7: SM pushes validated skills to agents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollDirectives(self, request, context):
        """R5: SM->agent directed directives. Agents dial out; the SM cannot
        dial agents, so SM-initiated work (firmware campaigns, marketplace
        skill installs) is queued at the SM and delivered on this poll.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportDirectiveResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportVerdict': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportVerdict,
                    request_deserializer=harkeniq__pb2.VerdictReport.FromString,
                    response_serializer=harkeniq__pb2.VerdictAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=harkeniq__pb2.AgentHeartbeat.FromString,
                    response_serializer=harkeniq__pb2.HeartbeatAck.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=harkeniq__pb2.AgentRegistration.FromString,
                    response_serializer=harkeniq__pb2.RegistrationAck.SerializeToString,
            ),
            'ReportAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAction,
                    request_deserializer=harkeniq__pb2.ActionReport.FromString,
                    response_serializer=harkeniq__pb2.ActionAck.SerializeToString,
            ),
            'PollActionDecisions': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActionDecisions,
                    request_deserializer=harkeniq__pb2.DecisionPoll.FromString,
                    response_serializer=harkeniq__pb2.DecisionList.SerializeToString,
            ),
            'PushSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.PushSkill,
                    request_deserializer=harkeniq__pb2.SkillDistribution.FromString,
                    response_serializer=harkeniq__pb2.SkillDistributionAck.SerializeToString,
            ),
            'PollDirectives': grpc.unary_unary_rpc_method_handler(
                    servicer.PollDirectives,
                    request_deserializer=harkeniq__pb2.DirectivePoll.FromString,
                    response_serializer=harkeniq__pb2.DirectiveList.SerializeToString,
            ),
            'ReportDirectiveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportDirectiveResult,
                    request_deserializer=harkeniq__pb2.DirectiveResult.FromString,
                    response_serializer=harkeniq__pb2.DirectiveAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harkeniq.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('harkeniq.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportVerdict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/ReportVerdict',
            harkeniq__pb2.VerdictReport.SerializeToString,
            harkeniq__pb2.VerdictAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/Heartbeat',
            harkeniq__pb2.AgentHeartbeat.SerializeToString,
            harkeniq__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/RegisterAgent',
            harkeniq__pb2.AgentRegistration.SerializeToString,
            harkeniq__pb2.RegistrationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/ReportAction',
            harkeniq__pb2.ActionReport.SerializeToString,
            harkeniq__pb2.ActionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollActionDecisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/PollActionDecisions',
            harkeniq__pb2.DecisionPoll.SerializeToString,
            harkeniq__pb2.DecisionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/PushSkill',
            harkeniq__pb2.SkillDistribution.SerializeToString,
            harkeniq__pb2.SkillDistributionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollDirectives(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/PollDirectives',
            harkeniq__pb2.DirectivePoll.SerializeToString,
            harkeniq__pb2.DirectiveList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportDirectiveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/ReportDirectiveResult',
            harkeniq__pb2.DirectiveResult.SerializeToString,
            harkeniq__pb2.DirectiveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SiteManagerServiceStub:
    """---------------------------------------------------------------------------
    SiteManagerService: Central Command → Site Manager
    CC dials SM to register, poll fleet, route approvals, and collect usage.
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSite = channel.unary_unary(
                '/harkeniq.v1.SiteManagerService/RegisterSite',
                request_serializer=harkeniq__pb2.SiteRegistration.SerializeToString,
                response_deserializer=harkeniq__pb2.SiteRegistrationAck.FromString,
                _registered_method=True)
        self.GetFleetSnapshot = channel.unary_unary(
                '/harkeniq.v1.SiteManagerService/GetFleetSnapshot',
                request_serializer=harkeniq__pb2.FleetSnapshotRequest.SerializeToString,
                response_deserializer=harkeniq__pb2.FleetSnapshot.FromString,
                _registered_method=True)
        self.RouteApproval = channel.unary_unary(
                '/harkeniq.v1.SiteManagerService/RouteApproval',
                request_serializer=harkeniq__pb2.ApprovalRouteRequest.SerializeToString,
                response_deserializer=harkeniq__pb2.ApprovalRouteAck.FromString,
                _registered_method=True)
        self.GetUsageSnapshot = channel.unary_unary(
                '/harkeniq.v1.SiteManagerService/GetUsageSnapshot',
                request_serializer=harkeniq__pb2.UsageSnapshotRequest.SerializeToString,
                response_deserializer=harkeniq__pb2.UsageSnapshot.FromString,
                _registered_method=True)
        self.PushPolicy = channel.unary_unary(
                '/harkeniq.v1.SiteManagerService/PushPolicy',
                request_serializer=harkeniq__pb2.PolicyUpdate.SerializeToString,
                response_deserializer=harkeniq__pb2.PolicyAck.FromString,
                _registered_method=True)
        self.InstallSkill = channel.unary_unary(
                '/harkeniq.v1.SiteManagerService/InstallSkill',
                request_serializer=harkeniq__pb2.SiteSkillInstall.SerializeToString,
                response_deserializer=harkeniq__pb2.SiteSkillInstallAck.FromString,
                _registered_method=True)


class SiteManagerServiceServicer:
    """---------------------------------------------------------------------------
    SiteManagerService: Central Command → Site Manager
    CC dials SM to register, poll fleet, route approvals, and collect usage.
    ---------------------------------------------------------------------------

    """

    def RegisterSite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFleetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouteApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSkill(self, request, context):
        """R5-2: CC pushes a marketplace skill to the site; the SM queues
        skill_install directives its agents pick up on their next poll.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiteManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSite': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSite,
                    request_deserializer=harkeniq__pb2.SiteRegistration.FromString,
                    response_serializer=harkeniq__pb2.SiteRegistrationAck.SerializeToString,
            ),
            'GetFleetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFleetSnapshot,
                    request_deserializer=harkeniq__pb2.FleetSnapshotRequest.FromString,
                    response_serializer=harkeniq__pb2.FleetSnapshot.SerializeToString,
            ),
            'RouteApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteApproval,
                    request_deserializer=harkeniq__pb2.ApprovalRouteRequest.FromString,
                    response_serializer=harkeniq__pb2.ApprovalRouteAck.SerializeToString,
            ),
            'GetUsageSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageSnapshot,
                    request_deserializer=harkeniq__pb2.UsageSnapshotRequest.FromString,
                    response_serializer=harkeniq__pb2.UsageSnapshot.SerializeToString,
            ),
            'PushPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.PushPolicy,
                    request_deserializer=harkeniq__pb2.PolicyUpdate.FromString,
                    response_serializer=harkeniq__pb2.PolicyAck.SerializeToString,
            ),
            'InstallSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallSkill,
                    request_deserializer=harkeniq__pb2.SiteSkillInstall.FromString,
                    response_serializer=harkeniq__pb2.SiteSkillInstallAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harkeniq.v1.SiteManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('harkeniq.v1.SiteManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SiteManagerService:
    """---------------------------------------------------------------------------
    SiteManagerService: Central Command → Site Manager
    CC dials SM to register, poll fleet, route approvals, and collect usage.
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def RegisterSite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.SiteManagerService/RegisterSite',
            harkeniq__pb2.SiteRegistration.SerializeToString,
            harkeniq__pb2.SiteRegistrationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFleetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.SiteManagerService/GetFleetSnapshot',
            harkeniq__pb2.FleetSnapshotRequest.SerializeToString,
            harkeniq__pb2.FleetSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouteApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.SiteManagerService/RouteApproval',
            harkeniq__pb2.ApprovalRouteRequest.SerializeToString,
            harkeniq__pb2.ApprovalRouteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.SiteManagerService/GetUsageSnapshot',
            harkeniq__pb2.UsageSnapshotRequest.SerializeToString,
            harkeniq__pb2.UsageSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.SiteManagerService/PushPolicy',
            harkeniq__pb2.PolicyUpdate.SerializeToString,
            harkeniq__pb2.PolicyAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.SiteManagerService/InstallSkill',
            harkeniq__pb2.SiteSkillInstall.SerializeToString,
            harkeniq__pb2.SiteSkillInstallAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
