# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from harkeniq.proto import harkeniq_pb2 as harkeniq__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in harkeniq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportVerdict = channel.unary_unary(
                '/harkeniq.v1.AgentService/ReportVerdict',
                request_serializer=harkeniq__pb2.VerdictReport.SerializeToString,
                response_deserializer=harkeniq__pb2.VerdictAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/harkeniq.v1.AgentService/Heartbeat',
                request_serializer=harkeniq__pb2.AgentHeartbeat.SerializeToString,
                response_deserializer=harkeniq__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/harkeniq.v1.AgentService/RegisterAgent',
                request_serializer=harkeniq__pb2.AgentRegistration.SerializeToString,
                response_deserializer=harkeniq__pb2.RegistrationAck.FromString,
                _registered_method=True)
        self.ReportAction = channel.unary_unary(
                '/harkeniq.v1.AgentService/ReportAction',
                request_serializer=harkeniq__pb2.ActionReport.SerializeToString,
                response_deserializer=harkeniq__pb2.ActionAck.FromString,
                _registered_method=True)
        self.PollActionDecisions = channel.unary_unary(
                '/harkeniq.v1.AgentService/PollActionDecisions',
                request_serializer=harkeniq__pb2.DecisionPoll.SerializeToString,
                response_deserializer=harkeniq__pb2.DecisionList.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportVerdict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollActionDecisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportVerdict': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportVerdict,
                    request_deserializer=harkeniq__pb2.VerdictReport.FromString,
                    response_serializer=harkeniq__pb2.VerdictAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=harkeniq__pb2.AgentHeartbeat.FromString,
                    response_serializer=harkeniq__pb2.HeartbeatAck.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=harkeniq__pb2.AgentRegistration.FromString,
                    response_serializer=harkeniq__pb2.RegistrationAck.SerializeToString,
            ),
            'ReportAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportAction,
                    request_deserializer=harkeniq__pb2.ActionReport.FromString,
                    response_serializer=harkeniq__pb2.ActionAck.SerializeToString,
            ),
            'PollActionDecisions': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActionDecisions,
                    request_deserializer=harkeniq__pb2.DecisionPoll.FromString,
                    response_serializer=harkeniq__pb2.DecisionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'harkeniq.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('harkeniq.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportVerdict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/ReportVerdict',
            harkeniq__pb2.VerdictReport.SerializeToString,
            harkeniq__pb2.VerdictAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/Heartbeat',
            harkeniq__pb2.AgentHeartbeat.SerializeToString,
            harkeniq__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/RegisterAgent',
            harkeniq__pb2.AgentRegistration.SerializeToString,
            harkeniq__pb2.RegistrationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/ReportAction',
            harkeniq__pb2.ActionReport.SerializeToString,
            harkeniq__pb2.ActionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollActionDecisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/harkeniq.v1.AgentService/PollActionDecisions',
            harkeniq__pb2.DecisionPoll.SerializeToString,
            harkeniq__pb2.DecisionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
